---
- name: Template Basic
  hosts: localhost
  tasks:
    - name: copy one file to another
      template:
        src=/home/clewis/Programing/Python/Mastering-Python_Networking-4th-Edition/Chp4_Ansible/Templates/file1
        dest=/home/clewis/Programing/Python/Mastering-Python_Networking-4th-Edition/Chp4_Ansible/Templates/file2