---
- name: Configure Access List
  hosts: "nxosv-devices"
  gather_facts: false
  connection: local

  vars:
    cli:
      host: "{{ ansible_host }}"
      username: "{{ ansible_user }}"
      password: "{{ ansible_ssh_pass }}"
      transport: cli
  
  tasks:
    - nxos_acl:
        name: border_inbound
        seq: 20
        action: deny
        proto: tcp
        src: 172.16.0.0/12
        dest: any
        log: enable
        state: present
    - nxos_acl:
        name: border_inbound
        seq: 30
        action: deny
        proto: tcp
        src: 192.168.0.0/16
        dest: any
        state: present
        log: enable
    - nxos_acl:
        name: border_inbound
        seq: 40
        action: permit
        proto: tcp
        src: any
        dest: 10.0.0.9/32
        dest_port_op: eq
        dest_port1: 22
        state: present
        log: enable
    - nxos_acl:
        name: border_inbound
        seq: 50
        action: permit
        proto: tcp
        src: any
        dest: 10.0.0.9/32
        dest_port_op: eq 
        dest_port1: 80
        state: present
        log: enable
    - nxos_acl:
        name: border_inbound
        seq: 60
        action: permit  
        proto: tcp
        src: any
        dest: any
        state: present
        log: enable
        established: enable
    - nxos_acl:
        name: border_inbound
        seq: 1000
        action: deny 
        proto: ip 
        src: any
        dest: any
        state: present
        log: enable
    - name: apply ingress acl to Ethernet 2/4
      nxos_acl_interface: 
        name: border_inbound
        interface: Ethernet2/4
        direction: ingress
        state: present



