---
- name: IOS command output for when clause
  hosts: iosxe_devices
  gather_facts: false
  tasks:
    - name: show hostname
      ios_command:
        commands:
          - show run | i hostname
      register: output

    - name: show output with when conditional
      when: output.stdout == ["hostname ansible-2"]
      debug:
        msg: '{{ output }}'