---
- name: Add Multiple Vlans
  hosts: "ansible-1"
  gather_facts: false
  connection: network_cli
  vars:
    vlan_numbers: [100, 200, 300]
  tasks:
    - name: add vlans
      ios_config:
        lines:
          - vlan {{ item }}
      loop: "{{ vlan_numbers }}"
      register: output